# This configuration file loads up before any MMV related stuff is set
# and it doesn't change anything on the final video, this file is mostly
# for configurations such as logging, namely Python stuff or QOL, let
# you name it.


[logging]
log_to_file = true
log_level = "info"  # critical, debug, error, info
log_format = "pretty"  # informational, pretty, economic, onlymessage

[flow]
stop_at_initialization = false